export const REPORT_CREATE_REQUEST = 'REPORT_CREATE_REQUEST'
export const REPORT_CREATE_SUCCESS = 'REPORT_CREATE_SUCCESS'
export const REPORT_CREATE_FAIL = 'REPORT_CREATE_FAIL'
export const REPORT_CREATE_RESET = 'REPORT_CREATE_RESET'

export const REPORT_DETAILS_REQUEST = 'REPORT_DETAILS_REQUEST'
export const REPORT_DETAILS_SUCCESS = 'REPORT_DETAILS_SUCCESS'
export const REPORT_DETAILS_FAIL = 'REPORT_DETAILS_FAIL'
export const REPORT_DETAILS_RESET = 'REPORT_DETAILS_RESET'

export const REPORT_UPDATE_REQUEST = 'REPORT_UPDATE_REQUEST'
export const REPORT_UPDATE_SUCCESS = 'REPORT_UPDATE_SUCCESS'
export const REPORT_UPDATE_FAIL = 'REPORT_UPDATE_FAIL'
export const REPORT_UPDATE_RESET = 'REPORT_UPDATE_RESET'

export const REPORT_ADMIN_UPDATE_REQUEST = 'REPORT_ADMIN_UPDATE_REQUEST'
export const REPORT_ADMIN_UPDATE_SUCCESS = 'REPORT_ADMIN_UPDATE_SUCCESS'
export const REPORT_ADMIN_UPDATE_FAIL = 'REPORT_ADMIN_UPDATE_FAIL'
export const REPORT_ADMIN_UPDATE_RESET = 'REPORT_ADMIN_UPDATE_RESET'

export const REPORT_DELETE_REQUEST = 'REPORT_DELETE_REQUEST'
export const REPORT_DELETE_SUCCESS = 'REPORT_DELETE_SUCCESS'
export const REPORT_DELETE_FAIL = 'REPORT_DELETE_FAIL'

export const REPORT_LIST_BY_EMPLOYEE_REQUEST = 'REPORT_LIST_BY_EMPLOYEE_REQUEST'
export const REPORT_LIST_BY_EMPLOYEE_SUCCESS = 'REPORT_LIST_BY_EMPLOYEE_SUCCESS'
export const REPORT_LIST_BY_EMPLOYEE_FAIL = 'REPORT_LIST_BY_EMPLOYEE_FAIL'
export const REPORT_LIST_BY_EMPLOYEE_RESET = 'REPORT_LIST_BY_EMPLOYEE_RESET'
